### ISSUE TITLE
After auto-update, several days ago, app name appears in Chinese 

### ISSUE THREAD

**Issue by erusev** [SelfControlApp/selfcontrol#454] opened 2017-08-21 07:03 UTC
![image](https://user-images.githubusercontent.com/184170/29507258-029afe92-8658-11e7-975f-42b1240fc135.png)

**Comment by cstigler** [comment] 2017-09-17 19:54
Hmm @erusev not sure what the issue could be there. Could you open up your Language and Region settings (in System Preferences) and share the complete list of your preferred languages (screenshot is fine)?

**Comment by erusev** [comment] 2017-09-18 08:18
Sure, here it is:

![image](https://user-images.githubusercontent.com/184170/30533649-1d34b984-9c63-11e7-9f2c-53fe3ee427cb.png)

**Comment by cstigler** [comment] 2017-09-19 04:43
Hm, thanks for the info - unfortunately I still have no clue what's causing this! It's good to know that Chinese is at least in your language list, though, which makes this a bit more explainable.

What appears to be happening is that your computer is failing to find the app name in English... and so is falling back to a further-back language on your list. We don't have Bulgarian, so it's using Chinese.

**Comment by cstigler** [comment] 2017-09-19 04:45
OK, @erusev, I have one idea which I hope will fix it. Can you try...

1. Delete the SelfControl app from your computer (including multiple copies if you have them)
2. Restart the computer
3. Download [this special version of SelfControl from this link](
Amazon S3selfcontrol
SelfControl-2.2.1-namefix.zip Latest version 
Overview
Properties
Permissions
Open  Download  Download as  Make public  Copy path 
Owner
glaciusxx
Last modified
Sep 18, 2017 9:43:29 PM
Etag
a675a742e38d1e2c3e62f6d9cbdf40b5
Storage class
Standard
Server side encryption
Size
2503924
Link
https://s3.amazonaws.com/selfcontrol/SelfControl-2.2.1-namefix.zip), put it in your Applications folder, and open it.
4. Try Spotlight again.

I made a change to our Info.plist which I hope will fix this!

**Comment by erusev** [comment] 2017-09-19 06:42
It worked! Thanks.

**Comment by cstigler** [comment] 2017-09-19 07:05
Awesome! Glad we could get that fixed

**Comment by ernsheong** [comment] 2017-11-17 13:13
This is happening to me as well. It's been a while, and I found it hilarious.

**Comment by cstigler** [comment] 2017-11-17 22:46
@ernsheong what version of SelfControl are you running? This should be fixed in version 2.2.2, which was released in mid-October. (The above "special version" was just a pre-release version to test the fix.)

**Comment by ernsheong** [comment] 2017-11-18 15:10
@cstigler thank you for your reply. I'm on the latest 2.2.2.

Alfred:
![image](https://user-images.githubusercontent.com/1343284/32981814-4ec17eb0-ccb5-11e7-8dc3-02e9bbf3b993.png)

Spotlight:
![image](https://user-images.githubusercontent.com/1343284/32981825-66dd7274-ccb5-11e7-923f-5ddcaa8b7048.png)

Language & Region:
![image](https://user-images.githubusercontent.com/1343284/32981827-784c58c2-ccb5-11e7-9931-4f2e4bedb7ff.png)

macOS version:
![image](https://user-images.githubusercontent.com/1343284/32981828-82fd5276-ccb5-11e7-857b-5bddbed90530.png)

Removing the Chinese Simplified language option "fixed" it for Spotlight.

**Comment by cstigler** [comment] 2017-11-19 01:49
@ernsheong huh, weird, I wonder what's going on this time. I'll look at it when I have a chance. Thanks for the heads-up.

**Comment by cstigler** [comment] 2017-11-19 01:59
@ernsheong TBH though I'm not sure why this is still happening - we have a `CFBundleDisplayName` for English that should be used. If you're a developer and feel like looking into it, please do!

**Comment by ernsheong** [comment] 2017-11-19 10:54
@cstigler from https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-110725, it looks like SelfControl is not adhering to the guideline:

> CFBundleDisplayName (String - iOS, macOS) specifies the display name of the bundle, visible to users and used by Siri. If you support localized names for your bundle, include this key in your app’s Info.plist file and in the InfoPlist.strings files of your app’s language subdirectories. If you localize this key, include a localized version of the CFBundleName key as well.

Also of note for testing:
> In macOS, before displaying a localized name for your bundle, the Finder compares the value of this key against the actual name of your bundle in the file system. If the two names match, the Finder proceeds to display the localized name from the appropriate InfoPlist.strings file of your bundle. If the names do not match, the Finder displays the file-system name.

I will raise a PR to add `CFBundleName` to the InfoPlist.strings for zh-Hans. I've tested it by deleting the Application, restarting the computer and adding back the bundle to Applications. Spotlight plays nice now.

**Comment by cstigler** [comment] 2017-11-19 18:58
Thank you @ernsheong, that is a great catch! The fix will be in the next released version after 2.2.2.

**Comment by ernsheong** [comment] 2020-03-23 05:14
This seems to have regressed in 2.3.2

**Comment by cstigler** [comment] 2020-03-23 05:47
@ernsheong 🤦‍♀️ thanks for pointing this out, this one drives me crazy

2.3.2 was just some UI changes (supporting Dark Mode) so I doubt that was it. Probably 2.3 when I [migrated the whole app to base localization](https://github.com/SelfControlApp/selfcontrol/commit/c17944154290bb4a4f7f91bd939f6c9b0c5e2331).

You were great at tracking down and fixing the problem last time, so if you see what I messed up this time a fix would be very welcome! Otherwise, I'll add it to my list :)

**Comment by cstigler** [comment] 2020-05-14 16:50
@ernsheong would you mind retesting to see if this is still an issue for you in SC 3.0, released today? I couldn't reproduce the issue, but I did make some tweaks to localization (eliminating some unnecessary localizations that  were included in the last few versions) which I'm hoping might've helped.

**Comment by ernsheong** [comment] 2020-05-15 03:38
Thanks. I upgraded but I still see Chinese. However, I don't wish to keep this issue open and I'm not so bothered by it. It could be something specific to my computer, but I don't think I want to spend more time debugging this... so feel free to close, we can try again in another issue if ncessary.

![image](https://user-images.githubusercontent.com/1343284/82008906-80ea6480-96a0-11ea-9caf-e476fe037eb4.png)

**Comment by cstigler** [comment] 2020-05-15 19:38
Makes sense! Thanks for the time and effort you've already contributed to debugging this. If I reproduce this at some point, or if somebody else has this problem, we'll reopen.

**Closed by cstigler** 2020-05-15 19:38 UTC
