### ISSUE TITLE
The first timer increment should be 1minute, then 15, 30 etc

### ISSUE THREAD

**Issue by atreeon** [SelfControlApp/selfcontrol#592] opened 2019-12-19 16:19 UTC
This will allow us to test our new blacklist without having to wait 15 minutes.

**Comment by DavidMunch** [comment] 2020-05-15 08:23
Refer #558.

**Comment by wenman-ualberta** [comment] 2022-04-05 07:17
Duplicate of #543

**Closed** 2023-12-21 15:13 UTC
