### ISSUE TITLE
Since Big Sur Mac Update, Self Control app isn't working.

### ISSUE THREAD

**Issue by Connor4real** [SelfControlApp/selfcontrol#651] opened 2020-11-18 00:53 UTC
My timer went to 0 and my long list of blocked websites completely vanished too. Now i Can't even add sites or start a timer. Keeps coming up with error 210

**Comment by RidhwaanDev** [comment] 2020-11-29 02:37
Yup, had the same issue. Nuked my Big Sur installation rolled back to  Catalina. Until this is fixed, I can't update to Big Sur.

**Comment by jaworek** [comment] 2020-12-05 14:25
My guess is that due to Apple changing stuff in the network stack something broke. From what I understood it may not be possible to setup SelfControl properly on Big Sur due to these limitations.
But maybe I'm wrong.

https://twitter.com/patrickwardle/status/1327726496203476992

https://sneak.berlin/20201112/your-computer-isnt-yours/

**Comment by alexander-kurz** [comment] 2020-12-31 09:42
@Connor4real I'm considering to upgrade my Mac to Big Sur but I'm hesitant, because of the problem you encountered. Does the SelfControl App still not work for you on Big Sur?
If SelfControl doesn't work properly on Big Sur, I guess I'll wait a bit longer before I'm going to upgrade.

**Comment by eleyine** [comment] 2021-01-07 18:13
Has anyone found a solution for this?

**Comment by cstigler** [comment] 2021-01-10 23:08
Hi folks, is anyone still having active issues with this? (@Connor4real @eleyine or anyone else?) And if so, what version of Big Sur are you on?

I've been on Big Sur since the summer, and have run SelfControl without issue. It's possible that there are certain system setups it doesn't work with. It's also possible that the issues are unrelated to Big Sur (just coincidentally timed).

If anyone is still having issues, can you please reply with:

- What's wrong (i.e. what you expected to happen, and what happened instead)
- What happened before you encountered issues (i.e. was it the first time you started SC after the upgrade, was a block running when you upgraded, etc)
- What version of SelfControl you're running
- Any other relevant info (VPN usage, non-admin user, etc)

And I'll try to fix things up for you. Thanks!

**Comment by calumdavey** [comment] 2021-01-15 15:51
Hi @cstigler. I can chime in here. I am running Mac OS 11.1 on a 2013 MacBook pro 13 inch. No VPN and I am the admin user. I am running SelfControl version 3.0.3., having re-installed after the upgrade to Mac OS 11. I was not running a block during the upgrade, but immediately after was unable to block sites -- SC seems like it is working (e.g. no errors and the count-down appears) but I can access sites on the block list. I deleted SC and re-installed but the problem is the same: not actually blocking any sites. 

Hope that helps,
Calum

**Comment by cstigler** [comment] 2021-01-18 23:10
Thanks for the info @calumdavey! Are you by any chance running Firefox, or otherwise could have DNS-over-HTTPS (DoH) turned on? I'd love to debug with you further and get things working for you. Could you email me at charlie+sc651@charliestigler.com and I'll help you out from there?

There's also a big update to SelfControl coming in a month-ish, so I can also pass you an alpha version of that to see if it works better...

**Comment by calumdavey** [comment] 2021-01-19 07:37
Thanks @cstigler, no Safari only, with no extensions. I'll shoot you an email, thanks!

**Comment by eleyine** [comment] 2021-01-20 19:58
@cstigler I used to have an issue with Self Control v 3.02 right after upgrading my OS to Mac OS 11.1 on a 2019 13" MacBook Pro. The block would only work for a couple of seconds and then it would reset, allowing me to start another block. My list did not vanish like OP. I do not use a VPN and I am an admin user. The problem resolved after I upgraded to Self Control v 3.03. It might have all been coincidental, I am not sure.

**Comment by cstigler** [comment] 2021-01-21 07:49
@eleyine thanks for the info! That was a known issue - 3.0.2 does not work with Big Sur. But I pushed a fix for that issue as 3.0.3 in September, so that should be fully resolved now.

**Comment by nikojankovic** [comment] 2021-01-24 03:44
I was going to comment that I'm also facing this issue (big sur 11.1 / 2019 16" mbp) but it seems that after a short while it does start blocking (this was also the first time running the app since the upgrade) - not sure if this helpful but thought it was worth mentioning.

**Comment by cstigler** [comment] 2021-01-27 08:07
Thanks for the info @nikojankovic ! Just to confirm, when you say "after a short while it does start blocking", do you just mean that it shows the "Loading" screen for a while after starting the block? Block start time varies depending on network connection so unfortunately is sometimes erratic (and is usually much longer for allowlist blocks). But that's probably not Big Sur related.

**Comment by mtrazzi** [comment] 2021-03-04 10:38
for reference, I'm on M1 bigsur and today it took me like 5m for it to start blocking sites (I'm on 3.0.3)

**Comment by cstigler** [comment] 2021-03-05 18:46
Hi @mtrazzi , that's unfortunate! Testing with the upcoming 4.0 alpha release (on Big Sur / Intel), I'm consistently seeing starts on 500+ site blocklists in under 15 seconds. If you'd like to get an early alpha version so you can confirm it's working better for you too, shoot me an email at charlie+sc651@charliestigler.com and I'll put you on the testing list.

**Comment by cstigler** [comment] 2021-03-05 18:48
Also, closing this issue since so far I haven't found an actual Big Sur related issue :) but reports for all the specific problems are still encouraged! And if anybody is dying to try out the new version to see if it fixes their issues, email me at the address above and I can add you to the early-access testing list (the first alpha version should be sent out in the next few weeks).

**Closed by cstigler** 2021-03-05 18:48 UTC
